INSERT INTO USER (ID, USERNAME, PASSWORD, PASSWORD_TYPE, ADMIN, FIRSTNAME, LASTNAME, CREATION_DATE) VALUES (1, 'admin', 'password', 'PLAIN', true, 'Bruce', 'Wayne', now());
INSERT INTO USER (ID, USERNAME, PASSWORD, PASSWORD_TYPE, ADMIN, FIRSTNAME, LASTNAME, CREATION_DATE) VALUES (2, 'user', 'password', 'PLAIN', false, 'Hans', 'Maulwurf', now());
