-- User
CREATE TABLE USER
(
  ID              INTEGER      NOT NULL AUTO_INCREMENT,
  USERNAME        VARCHAR(255) NOT NULL,
  PASSWORD        VARCHAR(255) NOT NULL,
  PASSWORD_TYPE   VARCHAR(255) NOT NULL,
  ADMIN           BOOLEAN NOT NULL,
  FIRSTNAME       VARCHAR(255),
  LASTNAME        VARCHAR(255),
  CREATION_DATE   DATE,
  PRIMARY KEY (ID)
);

-- Product
CREATE TABLE Product
(
  ID              INTEGER      NOT NULL AUTO_INCREMENT,
  NAME            VARCHAR(255) NOT NULL,
  TYPE            VARCHAR(255) NOT NULL,
  CREATION_DATE   DATE,
  PRIMARY KEY (ID)
);
